language: php

php:
 - 5.4
 - 5.5

before_script:
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install --no-interaction

script:
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml -c ./unit/phpunit.xml --bootstrap unit/bootstrap.php unit/

after_script:
 - php vendor/bin/coveralls -v